<nav class="navbar navbar-expand-md sticky-top py-3" style="background: var(--bs-primary-t);color: var(--bs-body-bg);">
        <div class="container"><a class="navbar-brand d-flex align-items-center" href="https://www.dariusdev.fr/"><img src="https://www.dariusdev.fr/img/DariusDevFull.webp" height="60px" width="216px" alt="Logo DariusDev"></a><button data-bs-toggle="collapse" class="navbar-toggler" data-bs-target="#navcol-2" style="border-style: solid;border-color: var(--bs-body-bg);"><span class="visually-hidden">Toggle navigation</span><svg xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" fill="currentColor" viewBox="0 0 16 16" class="bi bi-justify" style="color: var(--bs-body-bg);font-weight: bold;font-size: 32px;">
                    <path fill-rule="evenodd" d="M2 12.5a.5.5 0 0 1 .5-.5h11a.5.5 0 0 1 0 1h-11a.5.5 0 0 1-.5-.5zm0-3a.5.5 0 0 1 .5-.5h11a.5.5 0 0 1 0 1h-11a.5.5 0 0 1-.5-.5zm0-3a.5.5 0 0 1 .5-.5h11a.5.5 0 0 1 0 1h-11a.5.5 0 0 1-.5-.5zm0-3a.5.5 0 0 1 .5-.5h11a.5.5 0 0 1 0 1h-11a.5.5 0 0 1-.5-.5z"></path>
                </svg></button>
            <div class="collapse navbar-collapse" id="navcol-2" style="color: var(--bs-body-bg);">
                <ul class="navbar-nav ms-auto" style="color: var(--bs-body-bg);margin-top: 4px;">
                    <li class="nav-item" style="padding-top: 2px;padding-bottom: 2px;"><a class="nav-link active" href="https://dariusdev.fr/creations" style="color: var(--bs-body-bg);font-family: Lato-Bold;">Nos créations</a></li>
                    <li class="nav-item" style="margin-top: 2px;margin-bottom: 2px;"><a class="nav-link" href="https://dariusdev.fr/contact" style="color: var(--bs-body-bg);">Nous contacter</a></li>
                    <li class="nav-item" style="margin-top: 2px;margin-bottom: 2px;padding-right: 2px;padding-left: 2px;"><a class="btn" role="button" data-bss-hover-animate="pulse" href="https://dariusdev.fr/offres" style="background: var(--bs-secondary);color: var(--bs-body-bg);text-shadow: 0px 0px 8px var(--bs-black);">Voir nos offres</a></li>
                    <li class="nav-item dropdown" style="padding-top: 2px;padding-bottom: 2px;margin-left: 2px;"><a class="nav-link" aria-expanded="false" data-bs-toggle="dropdown" href="#" style="color: var(--bs-body-bg);">Menu&nbsp;<svg xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" fill="currentColor" viewBox="0 0 16 16" class="bi bi-justify" style="font-size: 20px;margin-bottom: 1px;">
                                <path fill-rule="evenodd" d="M2 12.5a.5.5 0 0 1 .5-.5h11a.5.5 0 0 1 0 1h-11a.5.5 0 0 1-.5-.5zm0-3a.5.5 0 0 1 .5-.5h11a.5.5 0 0 1 0 1h-11a.5.5 0 0 1-.5-.5zm0-3a.5.5 0 0 1 .5-.5h11a.5.5 0 0 1 0 1h-11a.5.5 0 0 1-.5-.5zm0-3a.5.5 0 0 1 .5-.5h11a.5.5 0 0 1 0 1h-11a.5.5 0 0 1-.5-.5z"></path>
                            </svg></a>
                        <div class="dropdown-menu dropdown-menu-end menu-bg-sm" style="border: 2px solid var(--bs-secondary);color: var(--bs-primary);"><a class="dropdown-item menu-bg-sm" href="https://dariusdev.fr/design" style="color: var(--bs-primary);">Web design</a><a class="dropdown-item menu-bg-sm" href="https://dariusdev.fr/dev" style="color: var(--bs-primary);">Développement</a><a class="dropdown-item menu-bg-sm" href="https://dariusdev.fr/hebergement" style="color: var(--bs-primary);">Hébergement</a><a class="dropdown-item menu-bg-sm" href="https://dariusdev.fr/optim" style="color: var(--bs-primary);">Optimisation &amp; services</a><a class="dropdown-item menu-bg-sm" href="https://dariusdev.fr/about" style="color: var(--bs-primary);">Qui sommes-nous ?</a><a class="dropdown-item menu-bg-sm" href="https://www.dariusdev.fr/" style="color: var(--bs-primary);">Revenir à l'accueil</a></div>
                    </li>
                </ul>
            </div>
        </div>
    </nav>